export const MARITAL_STATUS = {
  MARRIED: 1,
  WIDOWED: 2,
  SEPARATED: 3,
  DIVORCED: 4,
  SINGLE: 5
}

export const MARITAL_STATUS_LABEL = {
  [MARITAL_STATUS.MARRIED]: 'Married',
  [MARITAL_STATUS.WIDOWED]: 'Widowed',
  [MARITAL_STATUS.SEPARATED]: 'Separated',
  [MARITAL_STATUS.DIVORCED]: 'Divorced',
  [MARITAL_STATUS.SINGLE]: 'Single'
}

export const MARITAL_STATUS_OPTIONS = [
  { id: MARITAL_STATUS.SINGLE, name: MARITAL_STATUS_LABEL[MARITAL_STATUS.SINGLE] },

  { id: MARITAL_STATUS.MARRIED, name: MARITAL_STATUS_LABEL[MARITAL_STATUS.MARRIED] },
  { id: MARITAL_STATUS.DIVORCED, name: MARITAL_STATUS_LABEL[MARITAL_STATUS.DIVORCED] },

  { id: MARITAL_STATUS.WIDOWED, name: MARITAL_STATUS_LABEL[MARITAL_STATUS.WIDOWED] }
  // { id: MARITAL_STATUS.SEPARATED, name: MARITAL_STATUS_LABEL[MARITAL_STATUS.SEPARATED] },
]
