export const PERMISSIONS = {
  MANAGE_ALL_DEPARTMENT: 1,

  VIEW_GENERAL_INFO: 2,
  EDIT_GENERAL_INFO: 3,
  CREATE_GENERAL_INFO: 4,

  VIEW_CARD_INFO: 5,
  EDIT_CARD_INFO: 6,
  CREATE_CARD_INFO: 7,

  VIEW_CARD_IMAGE: 8,

  VIEW_CONTACT_INFO: 9,
  EDIT_CONTACT_INFO: 10,
  CREATE_CONTACT_INFO: 11,

  VIEW_ADDRESS_INFO: 12,
  EDIT_ADDRESS_INFO: 13,
  CREATE_ADDRESS_INFO: 14,

  VIEW_FAMILY_INFO: 15,
  EDIT_FAMILY_INFO: 16,
  CREATE_FAMILY_INFO: 17,

  VIEW_EMERGENCY_CONTACT_INFO: 18,
  EDIT_EMERGENCY_CONTACT_INFO: 19,
  CREATE_EMERGENCY_CONTACT_INFO: 20,

  VIEW_SOCIAL_INFO: 21,
  EDIT_SOCIAL_INFO: 22,
  CREATE_SOCIAL_INFO: 23,

  VIEW_VEHICLE_INFO: 24,
  EDIT_VEHICLE_INFO: 25,
  CREATE_VEHICLE_INFO: 26,

  CREATE_LEAVE_REQUEST: 27,
  VIEW_LEAVE_REQUEST_DETAIL: 28,
  VIEW_LIST_OF_SUBMITTED_REQUEST: 29,
  CANCEL_SUBMITTED_REQUEST: 30,
  ASK_TO_CANCEL_SUBMITTED_REQUEST: 31,
  VIEW_NOTI_LEAVE_REQUESTER: 32,
  MANAGE_LIST_EMPLOYEE: 33,
  MANAGE_STAFF_LEAVE_REQUESTER: 34,

  MANAGE_PERFORMANCE_APPRAISAL: 35,
  MANAGE_TEMPLATE_MANAGEMENT: 36,
  MANAGE_APPRAISAL_MANAGEMENT: 37,

  MANAGE_TEMPLATE_DETAIL: 38,

  MANAGE_LEAVE_INFO_BOARD: 39,
  MANAGE_COMPETENCY: 40,
  MANAGE_TEMPLATE_COMPETENCY: 41,
  MANAGE_ASS_COMPETENCY_MANAGEMENT: 42,

  APPROVER_VIEW_NOTIFICATION: 43,
  APPROVER_VIEW_LEAVE_REQUEST: 44,
  APPROVER_APPROVE_REQUEST: 45,
  APPROVER_REJECT_REQUEST: 46,
  APPROVER_REJECT_APPROVE_REQUEST: 47,
  APPROVER_APPROVE_LAYER_2: 48,

  MANAGE_ONBOARDING_EMPLOYEE: 49,
  MANAGE_REVIEW_360: 50
}

export const PROJECT_MANAGER_APPROVER_PERMISSIONS = [
  PERMISSIONS.APPROVER_VIEW_NOTIFICATION,
  PERMISSIONS.APPROVER_VIEW_LEAVE_REQUEST,
  PERMISSIONS.APPROVER_APPROVE_REQUEST,
  PERMISSIONS.APPROVER_REJECT_REQUEST,
  PERMISSIONS.APPROVER_REJECT_APPROVE_REQUEST,
  PERMISSIONS.APPROVER_APPROVE_LAYER_2
]
